<a href="https://colab.research.google.com/github/harshchaturkar/Mini-Project-repo/blob/main/assignment_24_Cf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("./Bank Marketing.csv")
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no


In [ ]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes


In [ ]:
df.tail()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no


In [ ]:
df.dtypes

,0
age,int64
job,object
marital,object
education,object
default,object
balance,int64
housing,object
loan,object
contact,object
day,int64


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [ ]:
df.isnull().sum()

,0
age,0
job,0
marital,0
education,0
default,0
balance,0
housing,0
loan,0
contact,0
day,0


In [ ]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000
mean,41.231948,1528.538524,15.658036,371.993818,2.508421,51.330407,0.832557
std,11.913369,3225.413326,8.420740,347.128386,2.722077,108.758282,2.292007
min,18.000000,-6847.000000,1.000000,2.000000,1.000000,-1.000000,0.000000
25%,32.000000,122.000000,8.000000,138.000000,1.000000,-1.000000,0.000000
50%,39.000000,550.000000,15.000000,255.000000,2.000000,-1.000000,0.000000
75%,49.000000,1708.000000,22.000000,496.000000,3.000000,20.750000,1.000000
max,95.000000,81204.000000,31.000000,3881.000000,63.000000,854.000000,58.000000


In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
x = df.drop("deposit", axis=1)
y = df["deposit"]

print("Independant feature :")
print(x.columns)

print("\nDependant feature :")
print(y.head)

Independant feature :
Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome'],
      dtype='object')

Dependant feature :
<bound method NDFrame.head of 0        yes
1        yes
2        yes
3        yes
4        yes
        ... 
11157     no
11158     no
11159     no
11160     no
11161     no
Name: deposit, Length: 11162, dtype: object>


In [ ]:
cat_cols = df.select_dtypes(include="object").columns
num_cols = df.select_dtypes(exclude="object").columns

print("Categorical columns :")
print(cat_cols)

print("\nNumerical columns :")
print(num_cols)
#cat_cols = cat_cols.drop("deposit")

Categorical columns :
Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'deposit'],
      dtype='object')

Numerical columns :
Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')


In [ ]:
encoded = pd.get_dummies(df[cat_cols])
encoded = encoded.astype(int)
encoded

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown,deposit_no,deposit_yes
0,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,1
1,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,1
2,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,1,0,1
3,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,1,0,1
4,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
11158,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
11159,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
11160,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,1,0,0,0,1,0


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled = scaler.fit_transform(df[num_cols])
scaled = pd.DataFrame(scaled, columns=num_cols)
scaled

,age,balance,day,duration,campaign,pdays,previous
0,1.491505,0.252525,-1.265746,1.930226,-0.554168,-0.481184,-0.363260
1,1.239676,-0.459974,-1.265746,3.154612,-0.554168,-0.481184,-0.363260
2,-0.019470,-0.080160,-1.265746,2.929901,-0.554168,-0.481184,-0.363260
3,1.155733,0.293762,-1.265746,0.596366,-0.554168,-0.481184,-0.363260
4,1.071790,-0.416876,-1.265746,0.867171,-0.186785,-0.481184,-0.363260
...,...,...,...,...,...,...,...
11157,-0.691015,-0.473616,0.515650,-0.331287,-0.554168,-0.481184,-0.363260
11158,-0.187357,-0.246658,0.040612,-0.832564,0.547981,-0.481184,-0.363260
11159,-0.774958,-0.464934,0.396891,-0.622258,-0.186785,-0.481184,-0.363260
11160,0.148416,-0.473926,-0.909466,-1.045752,-0.186785,1.109571,1.818332


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(encoded, y, test_size=0.2, random_state=42)

**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression

model_LOR = LogisticRegression()
model_LOR.fit(x_train, y_train)

LogisticRegression()

In [ ]:
pred_LOR = model_LOR.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy Score :")
print(accuracy_score(y_test, pred_LOR))
print("\nConfusion Matrix :")
print(confusion_matrix(y_test, pred_LOR))
print("\nClassification Report :")
print(classification_report(y_test, pred_LOR))

Accuracy Score :
1.0

Confusion Matrix :
[[1166    0]
 [   0 1067]]

Classification Report :
              precision    recall  f1-score   support

          no       1.00      1.00      1.00      1166
         yes       1.00      1.00      1.00      1067

    accuracy                           1.00      2233
   macro avg       1.00      1.00      1.00      2233
weighted avg       1.00      1.00      1.00      2233



**Decision Tree Classifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model_DT = DecisionTreeClassifier()
model_DT.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
pred_DT = model_DT.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy Score :")
print(accuracy_score(y_test, pred_DT))
print("\nConfusion Matrix :")
print(confusion_matrix(y_test, pred_DT))
print("\nClassification Report :")
print(classification_report(y_test, pred_DT))

Accuracy Score :
1.0

Confusion Matrix :
[[1166    0]
 [   0 1067]]

Classification Report :
              precision    recall  f1-score   support

          no       1.00      1.00      1.00      1166
         yes       1.00      1.00      1.00      1067

    accuracy                           1.00      2233
   macro avg       1.00      1.00      1.00      2233
weighted avg       1.00      1.00      1.00      2233



**Support Vector Machine (SVM)**

In [ ]:
from sklearn.svm import SVC

model_SVC = SVC()
model_SVC.fit(x_train, y_train)

SVC()

In [ ]:
pred_SVM = model_SVC.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy Score :")
print(accuracy_score(y_test, pred_SVM))
print("\nConfusion Matrix :")
print(confusion_matrix(y_test, pred_SVM))
print("\nClassification Report :")
print(classification_report(y_test, pred_SVM))

Accuracy Score :
1.0

Confusion Matrix :
[[1166    0]
 [   0 1067]]

Classification Report :
              precision    recall  f1-score   support

          no       1.00      1.00      1.00      1166
         yes       1.00      1.00      1.00      1067

    accuracy                           1.00      2233
   macro avg       1.00      1.00      1.00      2233
weighted avg       1.00      1.00      1.00      2233



**K-Nearest Neighbors (KNN)**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

model_KNN = KNeighborsClassifier(n_neighbors=5)
model_KNN.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
pred_KNN = model_KNN.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy Score :")
print(accuracy_score(y_test, pred_KNN))
print("\nConfusion Matrix :")
print(confusion_matrix(y_test, pred_KNN))
print("\nClassification Report :")
print(classification_report(y_test, pred_KNN))

Accuracy Score :
0.9968652037617555

Confusion Matrix :
[[1164    2]
 [   5 1062]]

Classification Report :
              precision    recall  f1-score   support

          no       1.00      1.00      1.00      1166
         yes       1.00      1.00      1.00      1067

    accuracy                           1.00      2233
   macro avg       1.00      1.00      1.00      2233
weighted avg       1.00      1.00      1.00      2233



**Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB

model_GNB = GaussianNB()
model_GNB.fit(x_train, y_train)

GaussianNB()

In [ ]:
pred_NB = model_GNB.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy Score :")
print(accuracy_score(y_test, pred_NB))
print("\nConfusion Matrix :")
print(confusion_matrix(y_test, pred_NB))
print("\nClassification Report :")
print(classification_report(y_test, pred_NB))

Accuracy Score :
1.0

Confusion Matrix :
[[1166    0]
 [   0 1067]]

Classification Report :
              precision    recall  f1-score   support

          no       1.00      1.00      1.00      1166
         yes       1.00      1.00      1.00      1067

    accuracy                           1.00      2233
   macro avg       1.00      1.00      1.00      2233
weighted avg       1.00      1.00      1.00      2233



In [ ]:
comparison_table = pd.DataFrame({
    "Model": ["Logistic Regression", "Decision Tree", "SVM", "KNN", "Naive Bayes"],
    "Accuracy": [1.0000, 1.0000, 1.0000, 0.9968, 1.0000],
    "Precision": [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
    "Recall": [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
    "F1-Score": [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]
})

print("Comparison Table")
print(comparison_table)

Comparison Table
                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression    1.0000        1.0     1.0       1.0
1        Decision Tree    1.0000        1.0     1.0       1.0
2                  SVM    1.0000        1.0     1.0       1.0
3                  KNN    0.9968        1.0     1.0       1.0
4          Naive Bayes    1.0000        1.0     1.0       1.0


In [ ]:
import joblib

best_classification_model = model_LOR

joblib.dump(best_classification_model, "best_classification_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(encoded.columns.tolist(), "columns.pkl")

print("Classification Model Saved!")
print("Scaler Saved!")
print("Columns Saved!")

Classification Model Saved!
Scaler Saved!
Columns Saved!
